### ISSUE TITLE
Java code

### ISSUE THREAD

**Issue by gaurav-kumar92** [KirkBushman/gfycat-android#1]
Hi, can you help me with java implementation, i had gone through the developer site of gfycat but it is confusing and i am not able to implement it, can you guide me how to implement that into Android in Java.

Thanks!

**Comment by KirkBushman** [comment]
Hi, 

It should already work with java. I used it with java before.
Kotlin and java both compile to jvm bytecode and produce .aar, so they are interchangeable, they can be used both in the same project.

First of all add jitpack as a repo to your root gradle.build:

```
allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }
    }
}
```

Then add the library as a dependency:

```
implementation 'com.github.KirkBushman:gfycat-android:1.0.0-alpha04'
```

Obtain the client: 

```
ClientCredentials creds = ClientCredentials(**Client Id**, **Client Secret**);
AuthManager auth = AuthManager(creds, true);

TokenBearer bearer = auth.getAuthToken(new SharedPrefsStorageManager(context));
GfycatClient client = auth.getGfycatClient(bearer);
```

Use the client: 

```
Gfycat gfycat = client.gfycatFromUrl(uri);
gfycat.mp4Url  // use the url for something
```
